#!/usr/bin/env python3
"""Derive the Esperanto->Ido gold set from the reviewed Ido->Esperanto one.

The ido->epo gold rows are (ido source, correct eo reference). Reversing a row
keeps a human-vetted pair: the eo reference becomes the source and the original
ido sentence becomes the reference. Nothing is hand-written here, so the output
is regenerable (`data/gold/ido_epo.tsv` -> `data/gold/epo_ido.tsv`).

Esperanto sources that occur in several rows (two ido spellings of one eo
sentence, e.g. 'Vu parolas.' / 'Tu parolas.' -> 'Vi parolas.') are merged into
one row whose reference lists every acceptable ido sentence separated by ' | ';
eval_translation.py scores a hypothesis against the best of them.

Caveat: eo->ido is inherently one-to-many (Ido has synonyms and optional
forms), so chrF against a single reference under-rates valid alternatives.
That is why alternatives are kept; extend the TSV by hand for more.

Usage: python3 scripts/build_gold_epo_ido.py
"""
from __future__ import annotations

import argparse
from collections import OrderedDict
from pathlib import Path

HEADER = """\
# Esperanto -> Ido gold evaluation set (generated)
# GENERATED by scripts/build_gold_epo_ido.py from data/gold/ido_epo.tsv -- do not edit by hand.
# Format: esperanto_source<TAB>reference_ido (alternatives separated by ' | ')<TAB>tags
# Each row is a reviewed ido->epo pair reversed; tags are inherited.
"""


def build(src: Path) -> list[tuple[str, list[str], list[str]]]:
    merged: "OrderedDict[str, tuple[list[str], list[str]]]" = OrderedDict()
    for line in src.read_text(encoding="utf-8").splitlines():
        if not line.strip() or line.lstrip().startswith("#"):
            continue
        parts = line.split("\t")
        if len(parts) < 2:
            continue
        ido, eo = parts[0].strip(), parts[1].strip()
        tags = [t.strip() for t in parts[2].split(",")] if len(parts) > 2 else []
        refs, all_tags = merged.setdefault(eo, ([], []))
        if ido not in refs:
            refs.append(ido)
        all_tags.extend(t for t in tags if t not in all_tags)
    return [(eo, refs, tags) for eo, (refs, tags) in merged.items()]


def main() -> int:
    here = Path(__file__).resolve().parent.parent
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--src", type=Path, default=here / "data/gold/ido_epo.tsv")
    ap.add_argument("--out", type=Path, default=here / "data/gold/epo_ido.tsv")
    args = ap.parse_args()
    rows = build(args.src)
    body = "".join(f"{eo}\t{' | '.join(refs)}\t{','.join(tags)}\n" for eo, refs, tags in rows)
    args.out.write_text(HEADER + body, encoding="utf-8")
    print(f"wrote {len(rows)} rows to {args.out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
