#!/usr/bin/env python3
"""Esperanto-first epo->ido benchmark sampled from Tatoeba.

data/gold/epo_ido.tsv is the ido->epo gold reversed, so it only holds Ido
sentences that were already worth reviewing and tends to flatter epo->ido. This
set starts from real *Esperanto* sentences instead: Tatoeba pairs (human Ido
translations, built by llm/data/build_tatoeba_pairs.py) filtered to plain,
checkable sentences, then a seeded random sample.

Caveats: Tatoeba's Ido side is often a free translation or contains slips, so
chrF against one reference caps well below 100; read the trend, not the level.
Sentences already in epo_ido.tsv are excluded. Tatoeba text is CC BY 2.0 FR.

Filters: 4-12 words, no digits, ends with . ? !, no '*' (unknown-word marks in
the pair file). Deterministic for a given input and --seed.

Usage: python3 scripts/build_gold_epo_ido_tatoeba.py [--src PATH] [--n 300] [--seed 1]
"""
from __future__ import annotations

import argparse
import json
import random
import re
from pathlib import Path

HEADER = """\
# Esperanto -> Ido benchmark sampled from Tatoeba (generated)
# GENERATED by scripts/build_gold_epo_ido_tatoeba.py -- do not edit by hand.
# Source: Tatoeba (https://tatoeba.org), CC BY 2.0 FR. Reference = Tatoeba's Ido translation.
# Format: esperanto_source<TAB>reference_ido<TAB>tags
"""


def usable(src: str, tgt: str) -> bool:
    return (4 <= len(src.split()) <= 12
            and not re.search(r"\d", src + tgt)
            and src[-1] in ".?!" and "*" not in tgt)


def build(src: Path, exclude: set[str], n: int, seed: int) -> list[tuple[str, str]]:
    seen: dict[str, str] = {}
    for line in src.read_text(encoding="utf-8").splitlines():
        r = json.loads(line)
        if r["src_lang"] != "epo" or not usable(r["src"], r["tgt"]):
            continue
        if r["src"] in exclude or r["src"] in seen:
            continue
        seen[r["src"]] = r["tgt"]
    pool = sorted(seen.items())
    random.Random(seed).shuffle(pool)
    return sorted(pool[:n])


def main() -> int:
    here = Path(__file__).resolve().parent.parent
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--src", type=Path,
                    default=here.parent / "llm/data/out/tatoeba_io_eo.jsonl")
    ap.add_argument("--existing", type=Path, default=here / "data/gold/epo_ido.tsv")
    ap.add_argument("--out", type=Path, default=here / "data/gold/epo_ido_tatoeba.tsv")
    ap.add_argument("--n", type=int, default=300)
    ap.add_argument("--seed", type=int, default=1)
    args = ap.parse_args()

    exclude = {l.split("\t")[0] for l in args.existing.read_text(encoding="utf-8").splitlines()
               if l.strip() and not l.startswith("#")}
    rows = build(args.src, exclude, args.n, args.seed)
    args.out.write_text(
        HEADER + "".join(f"{s}\t{t}\ttatoeba\n" for s, t in rows), encoding="utf-8")
    print(f"wrote {len(rows)} rows to {args.out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
