#!/usr/bin/env python3
"""Extract closed-class io↔eo pairs from structured wiki tables (roadmap #2).

Sources (both inside the io.wikipedia dump already consumed by the pipeline —
fully offline, regeneratable, auditable):

  1. "Komparo inter Ido ed Esperanto" — the pronoun comparison table gives a
     direct io↔eo mapping (me→mi, il(u)→li, on(u)→oni, …). Cells annotated
     with a footnote marker (¹ ² ³) are emitted under the *qualified* source
     name: the page itself flags them as theoretical/contested (e.g. tu→ci¹
     "ci nur existas teorie"), so they must not outrank live extractions.

  2. "Gramatiko di Ido" § "Tabelo plu granda" — the Ido correlative grid.
     The page is Ido-only; the Esperanto side is *generated by rule* from the
     grid position: column → EO series prefix (qua→ki-, ita→ti-, ula→i-,
     irga→i-…ajn, nula→neni-, omna→ĉi-) and row → EO category suffix
     (Individuo→-u, Kozo→-o, Pluralo→-uj, Loko→-e, Tempo→-am, Qualeso→-a,
     Maniero→-el, Motivo→-al, Quanto→-om; the unlabeled determiner row →-u).
     This grid correspondence is a documented linguistic rule, not a word
     list — Esperanto's correlative system is fully regular by construction.
     The page's own footnotes are also applied as rules: the ita-series may
     drop its initial i- (ita→ta, ito→to), and ula-/nula- compounds may
     syncopate the first -a- (ulatempe→ultempe).

Skipped on purpose: the "Posesivo (di …)" row (EO -es possessive semantics
don't align with Ido "di X" — 'di qua' is handled upstream), the adjectival
quantity row (no single-word EO equivalent), and the second indefinite table
(altra/singla/… — suppletive in EO, not derivable by rule; those words are
regular open extractions anyway).

Output: work/closed_class.json in the standard source-file format consumed by
build_one_big_bidix_json.py. Source names: 'closed_class_tables' (rank 0 in
conflict_resolution) and 'closed_class_tables_qualified' (default rank).

Usage: python3 scripts/parse_closed_class.py [-v]
"""
from __future__ import annotations

import argparse
import bz2
import re
import sys
import xml.etree.ElementTree as ET
from pathlib import Path
from typing import Dict, Iterator, List, Optional, Tuple

sys.path.insert(0, str(Path(__file__).resolve().parent))
from _common import write_json, configure_logging
import logging

DUMP_DEFAULT = Path(__file__).resolve().parents[1] / "data/raw/iowiki-latest-pages-articles.xml.bz2"
OUT_DEFAULT = Path(__file__).resolve().parents[1] / "work/closed_class.json"

PAGE_PRONOUNS = "Komparo inter Ido ed Esperanto"
PAGE_GRAMMAR = "Gramatiko di Ido"

SOURCE = "closed_class_tables"
SOURCE_QUALIFIED = "closed_class_tables_qualified"

_FOOTNOTE_RE = re.compile(r"[¹²³⁴⁵]|&lt;sup&gt;.*?&lt;/sup&gt;|<sup>.*?</sup>")


# --------------------------------------------------------------------------- #
# Dump page extraction
# --------------------------------------------------------------------------- #
def extract_pages(dump: Path, wanted: List[str]) -> Dict[str, Tuple[str, str]]:
    """Return {title: (revid, wikitext)} for the wanted titles; early exit."""
    remaining = set(wanted)
    found: Dict[str, Tuple[str, str]] = {}
    with bz2.open(dump, "rb") as f:
        for _event, elem in ET.iterparse(f, events=["end"]):
            if not elem.tag.endswith("}page"):
                continue
            title_el = elem.find(".//{*}title")
            title = title_el.text if title_el is not None else ""
            if title in remaining:
                rev_el = elem.find(".//{*}revision/{*}id")
                text_el = elem.find(".//{*}revision/{*}text")
                revid = rev_el.text if rev_el is not None else ""
                text = text_el.text if text_el is not None and text_el.text else ""
                found[title] = (revid, text)
                remaining.discard(title)
            elem.clear()
            if not remaining:
                break
    return found


# --------------------------------------------------------------------------- #
# Minimal wikitext table parsing
# --------------------------------------------------------------------------- #
def iter_tables(wikitext: str) -> Iterator[Tuple[str, List[List[Tuple[str, str]]]]]:
    """Yield (preceding_context, rows) per {| … |} table.

    A row is a list of (kind, cell) with kind '!' (header) or '|' (data).
    preceding_context is the text between the previous table (or start) and
    this one, so callers can match tables by section heading / caption.
    """
    pos = 0
    for m in re.finditer(r"^\{\|.*?^\|\}", wikitext, re.DOTALL | re.MULTILINE):
        context = wikitext[pos:m.start()]
        pos = m.end()
        body = m.group(0)
        rows: List[List[Tuple[str, str]]] = []
        current: List[Tuple[str, str]] = []
        for line in body.splitlines()[1:-1]:
            line = line.strip()
            if line.startswith("|+"):
                context += line  # caption participates in matching
                continue
            if line.startswith("|-"):
                if current:
                    rows.append(current)
                current = []
                continue
            if line.startswith("!") or line.startswith("|"):
                kind = line[0]
                rest = line[1:]
                # split inline multi-cells (!!  or ||)
                parts = re.split(r"\|\||!!", rest) if kind == "|" or kind == "!" else [rest]
                for part in parts:
                    # strip cell attributes: 'style="…" | value' → value
                    if "|" in part:
                        attr, _, val = part.rpartition("|")
                        # only treat as attribute if the left side looks like one
                        if re.search(r"=|colspan|rowspan|style|background", attr):
                            part = val
                    current.append((kind, part.strip()))
        if current:
            rows.append(current)
        yield context, rows


def _clean_cell(cell: str) -> str:
    cell = re.sub(r"&quot;", '"', cell)
    cell = re.sub(r"''+", "", cell)
    cell = re.sub(r"\[\[(?:[^|\]]*\|)?([^\]]*)\]\]", r"\1", cell)
    return cell.strip()


# --------------------------------------------------------------------------- #
# Entry assembly
# --------------------------------------------------------------------------- #
def make_entry(lemma: str, pos: str, eo: str, source: str, meta: Dict[str, str]) -> Dict:
    return {
        "lemma": lemma,
        "source": source,
        "pos": pos,
        "translations": [
            {"term": eo, "lang": "eo", "confidence": 1.0, "source": source}
        ],
        # provenance is what build_one_big folds into _all_sources →
        # bidix_big 'provenance', which export_apertium's monodix builder
        # checks to grant closed-class POS/paradigm authority.
        "provenance": [{"source": source}],
        "metadata": meta,
    }


# --------------------------------------------------------------------------- #
# 1. Pronoun table (Komparo inter Ido ed Esperanto)
# --------------------------------------------------------------------------- #
def parse_pronoun_table(wikitext: str, revid: str) -> List[Dict]:
    entries: List[Dict] = []
    for context, rows in iter_tables(wikitext):
        if "Pronomi" not in context:
            continue
        ido_cells: List[str] = []
        eo_cells: List[str] = []
        for row in rows:
            labels = [c for k, c in row if k == "!"]
            data = [c for k, c in row if k == "|"]
            if labels and _clean_cell(labels[0]) == "Ido":
                ido_cells = [_clean_cell(c) for c in data]
            elif labels and _clean_cell(labels[0]) == "Esperanto":
                eo_cells = [_clean_cell(c) for c in data]
        if not ido_cells or not eo_cells:
            continue
        for io_cell, eo_cell in zip(ido_cells, eo_cells):
            if not io_cell or not eo_cell:
                continue  # eli/oli columns have no EO equivalent
            qualified = bool(_FOOTNOTE_RE.search(eo_cell))
            eo_clean = _FOOTNOTE_RE.sub("", eo_cell).strip()
            # 'ĝi / ri' → first alternative is the table's primary value
            eo_primary = re.split(r"\s*/\s*", eo_clean)[0].strip()
            if not eo_primary:
                continue
            # 'il(u)' → lemmas il + ilu
            base = io_cell.replace(" ", "")
            m = re.match(r"^([a-z]+)\(([a-z]+)\)$", base)
            lemmas = [m.group(1), m.group(1) + m.group(2)] if m else [base]
            src = SOURCE_QUALIFIED if qualified else SOURCE
            for lemma in lemmas:
                entries.append(make_entry(
                    lemma, "prn", eo_primary, src,
                    {"page": PAGE_PRONOUNS, "revid": revid,
                     "table": "Pronomi", "cell": io_cell + "→" + eo_cell},
                ))
        break
    return entries


# --------------------------------------------------------------------------- #
# 2. Correlative grid (Gramatiko di Ido, "Tabelo plu granda")
# --------------------------------------------------------------------------- #
# column index → EO series prefix; None marks the irga column (i- + ' ajn')
COL_PREFIXES: List[Optional[str]] = ["ki", "ti", "i", None, "neni", "ĉi"]

# row label (lowercased, first header cell) → (EO suffix, Apertium POS)
# NOTE: quantity row uses pos 'prn' (closed-class-protected) — 'adv' would let
# the -o ending flip it to noun in build_one_big_bidix_json's POS sanity pass.
ROW_SPECS: Dict[str, Tuple[str, str]] = {
    "": ("u", "adj"),                       # unlabeled determiner row (omna, ita, …)
    "individuo": ("u", "prn"),
    "kozo": ("o", "prn"),
    "pluralo": ("uj", "prn"),
    "motivo": ("al", "adv"),                # pro quo→kial, pro ito→tial, …
    "loko": ("e", "adv"),
    "tempo": ("am", "adv"),
    "qualeso": ("a", "adj"),
    "maniero": ("el", "adv"),
    "quanto substantivala": ("om", "prn"),
    # skipped: 'posesivo' (di …) and 'quanto adjetivala' — see module docstring
}


def _grid_eo(col: int, suffix: str) -> str:
    prefix = COL_PREFIXES[col]
    if prefix is None:  # irga = "any at all" → EO i- series + ajn
        return "i" + suffix + " ajn"
    return prefix + suffix


def _cell_lemmas(cell: str) -> List[str]:
    """Split a grid cell into lemma alternatives (<br>, comma)."""
    cell = re.sub(r"&lt;br&gt;|<br\s*/?>", ",", cell)
    return [p.strip() for p in cell.split(",") if p.strip()]


def _variants(lemma: str, col: int) -> List[str]:
    """Apply the page's own footnote rules to derive attested short variants."""
    out = [lemma]
    # footnote 1: the ita series may drop its initial i- (ita→ta, pro ito→pro to)
    if col == 1:
        short = re.sub(r"\bit", "t", lemma)
        if short != lemma:
            out.append(short)
    # footnote 2: ula-/nula- compounds may syncopate the first -a-
    m = re.match(r"^(ul|nul)a(\w{4,})$", lemma)
    if m:
        out.append(m.group(1) + m.group(2))
    return out


def parse_correlative_grid(wikitext: str, revid: str) -> List[Dict]:
    entries: List[Dict] = []
    for context, rows in iter_tables(wikitext):
        if "Tabelo plu granda" not in context:
            continue
        for row in rows:
            labels = [_clean_cell(c) for k, c in row if k == "!"]
            data = [_clean_cell(c) for k, c in row if k == "|"]
            if len(data) != len(COL_PREFIXES):
                continue  # header / malformed rows
            label = labels[0].lower() if labels else ""
            label = re.sub(r"\s+", " ", label).strip()
            if label not in ROW_SPECS:
                continue
            # the unlabeled determiner row arrives with empty header cells
            suffix, pos = ROW_SPECS[label]
            for col, cell in enumerate(data):
                for lemma in _cell_lemmas(cell):
                    if not lemma or not re.match(r"^[a-z]+( [a-z]+)?$", lemma):
                        continue
                    eo = _grid_eo(col, suffix)
                    for variant in _variants(lemma, col):
                        entries.append(make_entry(
                            variant, pos, eo, SOURCE,
                            {"page": PAGE_GRAMMAR, "revid": revid,
                             "table": "Tabelo plu granda",
                             "row": label or "(determiner)",
                             "cell": lemma + "→" + eo},
                        ))
        break
    return entries


# --------------------------------------------------------------------------- #
# Main
# --------------------------------------------------------------------------- #
def main(argv) -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--input", type=Path, default=DUMP_DEFAULT)
    ap.add_argument("--out", type=Path, default=OUT_DEFAULT)
    ap.add_argument("-v", "--verbose", action="count", default=0)
    args = ap.parse_args(list(argv))
    configure_logging(args.verbose)

    logging.info("Scanning %s for source pages…", args.input)
    pages = extract_pages(args.input, [PAGE_PRONOUNS, PAGE_GRAMMAR])
    for title in (PAGE_PRONOUNS, PAGE_GRAMMAR):
        if title not in pages:
            logging.error("Page not found in dump: %s", title)
            return 1
        logging.info("Found %s (revid %s)", title, pages[title][0])

    entries: List[Dict] = []
    revid_prn, text_prn = pages[PAGE_PRONOUNS]
    revid_gram, text_gram = pages[PAGE_GRAMMAR]
    prn = parse_pronoun_table(text_prn, revid_prn)
    grid = parse_correlative_grid(text_gram, revid_gram)
    entries.extend(prn)
    entries.extend(grid)
    logging.info("Extracted %d pronoun pairs (%d qualified), %d grid pairs",
                 len(prn), sum(1 for e in prn if e["source"] == SOURCE_QUALIFIED),
                 len(grid))

    # One authoritative EO per (lemma, pos): when a lemma appears in multiple
    # grid rows with the same POS (the Qualeso row lists bare 'omna'/'ula' as
    # secondary alternatives of 'omnaspeca'/'ulaspeca'), the FIRST row wins —
    # table order puts the primary determiner reading first (omna→ĉiu), and a
    # second rank-0 term would tie and hand the win back to insertion order.
    # The secondary reading (omna→ĉia) stays visible via the open sources.
    seen = set()
    unique: List[Dict] = []
    for e in entries:
        key = (e["lemma"], e["pos"], e["source"])
        if key not in seen:
            seen.add(key)
            unique.append(e)

    out = {
        "metadata": {
            "source_name": SOURCE,
            "description": (
                "Closed-class io↔eo pairs extracted from structured tables in the "
                "io.wikipedia dump (pronoun comparison table + correlative grid with "
                "rule-generated EO side). See parse_closed_class.py docstring."
            ),
            "pages": {
                PAGE_PRONOUNS: {"revid": revid_prn},
                PAGE_GRAMMAR: {"revid": revid_gram},
            },
            "statistics": {"total_entries": len(unique)},
        },
        "entries": unique,
    }
    write_json(args.out, out)
    logging.info("Wrote %s (%d entries)", args.out, len(unique))
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
